`.lastRequest` <- 10

`.IBAPI.VERSION` <- "clientV63" # client Version 63

`.twsOutgoingMSG` <-
  list(REQ_MKT_DATA = "1",
       CANCEL_MKT_DATA = "2",
       PLACE_ORDER = "3",
       CANCEL_ORDER = "4",
       REQ_OPEN_ORDERS = "5",
       REQ_ACCOUNT_DATA = "6",
       REQ_EXECUTIONS = "7",
       REQ_IDS = "8",
       REQ_CONTRACT_DATA = "9",
       REQ_MKT_DEPTH = "10",
       CANCEL_MKT_DEPTH = "11",
       REQ_NEWS_BULLETINS = "12",
       CANCEL_NEWS_BULLETINS = "13",
       SET_SERVER_LOGLEVEL = "14",
       REQ_AUTO_OPEN_ORDERS = "15",
       REQ_ALL_OPEN_ORDERS = "16",
       REQ_MANAGED_ACCTS = "17",
       REQ_FA = "18",
       REPLACE_FA = "19",
       REQ_HISTORICAL_DATA = "20",
       EXERCISE_OPTIONS = "21",
       REQ_SCANNER_SUBSCRIPTION = "22",
       CANCEL_SCANNER_SUBSCRIPTION = "23",
       REQ_SCANNER_PARAMETERS = "24",
       CANCEL_HISTORICAL_DATA = "25",
       REQ_CURRENT_TIME = "49",
       REQ_REAL_TIME_BARS = "50",
       CANCEL_REAL_TIME_BARS = "51",
       REQ_FUNDAMENTAL_DATA = "52",
       CANCEL_FUNDAMENTAL_DATA = "53",
       REQ_CALC_IMPLIED_VOLAT = "54",
       REQ_CALC_OPTION_PRICE = "55",
       CANCEL_CALC_IMPLIED_VOLAT = "56",
       CANCEL_CALC_OPTION_PRICE = "57",
       REQ_GLOBAL_CANCEL = "58",
       REQ_MARKET_DATA_TYPE = "59",
       REQ_POSITIONS = "61",
       REQ_ACCOUNT_SUMMARY = "62",
       CANCEL_ACCOUNT_SUMMARY = "63",
       CANCEL_POSITIONS = "64",
       VERIFY_REQUEST = "65",
       VERIFY_MESSAGE = "66",
       QUERY_DISPLAY_GROUPS = "67",
       SUBSCRIBE_TO_GROUP_EVENTS = "68",
       UPDATE_DISPLAY_GROUP = "69",
       UNSUBSCRIBE_FROM_GROUP_EVENTS = "70",
       START_API = "71",
       VERIFY_AND_AUTH_REQUEST  =  "72",
       VERIFY_AND_AUTH_MESSAGE  =  "73",
       REQUEST_POSITIONS_MULTI  =  "74",
       CANCEL_POSITIONS_MULTI  =  "75",
       REQUEST_ACCOUNT_UPDATES_MULTI  =  "76",
       CANCEL_ACCOUNT_UPDATES_MULTI  =  "77",
       REQUEST_SECURITY_DEFINITION_OPTIONAL_PARAMETERS  =  "78",
       REQUEST_SOFT_DOLLAR_TIERS  =  "79",
       REQUEST_FAMILY_CODES  =  "80",
       REQUEST_MATCHING_SYMBOLS  =  "81",
       REQUEST_MKT_DEPTH_EXCHANGES  =  "82",
       REQUEST_SMART_COMPONENTS  =  "83",
       REQUEST_NEWS_ARTICLE  =  "84",
       REQUEST_NEWS_PROVIDERS  =  "85",
       REQUEST_HISTORICAL_NEWS  =  "86",
       REQUEST_HEAD_TIMESTAMP  =  "87",
       REQUEST_HISTOGRAM_DATA  =  "88",
       CANCEL_HISTOGRAM_DATA  =  "89",
       CANCEL_HEAD_TIMESTAMP  =  "90",
       REQUEST_MARKET_RULE  =  "91",
       REQ_PNL  =  "92",
       CANCEL_PNL  =  "93",
       REQ_PNL_SINGLE  =  "94",
       CANCEL_PNL_SINGLE  =  "95",
       REQ_HISTORICAL_TICKS  =  "96",
       REQ_TICK_BY_TICK_DATA  =  "97",
       CANCEL_TICK_BY_TICK_DATA  =  "98",
       REQ_COMPLETED_ORDERS  =  "99")
   
`.twsIncomingMSG` <-
  list(NotValid = "-1",
       TICK_PRICE = "1",
       TICK_SIZE = "2",
       ORDER_STATUS = "3",
       ERR_MSG = "4",
       OPEN_ORDER = "5",
       ACCT_VALUE = "6",
       PORTFOLIO_VALUE = "7",
       ACCT_UPDATE_TIME = "8",
       NEXT_VALID_ID = "9",
       CONTRACT_DATA = "10",
       EXECUTION_DATA = "11",
       MARKET_DEPTH = "12",
       MARKET_DEPTH_L2 = "13",
       NEWS_BULLETINS = "14",
       MANAGED_ACCTS = "15",
       RECEIVE_FA = "16",
       HISTORICAL_DATA = "17",
       BOND_CONTRACT_DATA = "18",
       SCANNER_PARAMETERS = "19",
       SCANNER_DATA = "20",
       TICK_OPTION_COMPUTATION = "21",
       TICK_GENERIC = "45",
       TICK_STRING = "46",
       TICK_EFP = "47",
       CURRENT_TIME = "49",
       REAL_TIME_BARS = "50",
       FUNDAMENTAL_DATA = "51",
       CONTRACT_DATA_END = "52",
       OPEN_ORDER_END = "53",
       ACCT_DOWNLOAD_END = "54",
       EXECUTION_DATA_END = "55",
       DELTA_NEUTRAL_VALIDATION = "56",
       TICK_SNAPSHOT_END = "57",
       MARKET_DATA_TYPE = "58",
       COMMISSION_REPORT = "59",
       POSITION_DATA = "61",
       POSITION_END = "62",
       ACCOUNT_SUMMARY = "63",
       ACCOUNT_SUMMARY_END = "64",
       VERIFY_MESSAGE_API = "65",
       VERIFY_COMPLETED = "66",
       DISPLAY_GROUP_LIST = "67",
       DISPLAY_GROUP_UPDATED = "68",
       VERIFY_AND_AUTHMESSAGE_API  = "69",
       VERIFY_ANDAUTH_COMPLETED  = "70",
       POSITION_MULTI  = "71",
       POSITION_MULTI_END  = "72",
       ACCOUNT_UPDATE_MULTI  = "73",
       ACCOUNT_UPDATE_MULTI_END  = "74",
       SECURITY_DEFINITION_OPTION_PARAMETER  = "75",
       SECURITY_DEFINITION_OPTION_PARAMETER_END  = "76",
       SOFT_DOLLAR_TIER  = "77",
       FAMILY_CODES  = "78",
       SYMBOL_SAMPLES  = "79",
       MKT_DEPTH_EXCHANGES  = "80",
       TICK_REQ_PARAMS  = "81",
       SMART_COMPONENTS  = "82",
       NEWS_ARTICLE  = "83",
       TICK_NEWS  = "84",
       NEWS_PROVIDERS  = "85",
       HISTORICAL_NEWS  = "86",
       HISTORICAL_NEWS_END  = "87",
       HEAD_TIMESTAMP  = "88",
       HISTOGRAM_DATA  = "89",
       HISTORICAL_DATA_UPDATE  = "90",
       REROUTE_MKTDATA_REQ  = "91",
       REROUTE_MKTDEPTH_REQ  = "92",
       MARKET_RULE  = "93",
       PNL  = "94",
       PNL_SINGLE  = "95",
       HISTORICAL_TICK  = "96",
       HISTORICAL_TICK_BID_ASK  = "97",
       HISTORICAL_TICK_LAST  = "98",
       TICK_BY_TICK  = "99",
       ORDER_BOUND  = "100",
       COMPLETED_ORDER  = "101",
       COMPLETED_ORDER_SEND  = "102")


.twsMinServerVer <- list(
          MIN_VERSION  = "38",
          HISTORICAL_DATA  = "24",
          CURRENT_TIME  = "33",
          REAL_TIME_BARS  = "34",
          SCALE_ORDERS  = "35",
          SNAPSHOT_MKT_DATA  = "35",
          SSHORT_COMBO_LEGS  = "35",
          WHAT_IF_ORDERS  = "36",
          CONTRACT_CONID  = "37",
          PTA_ORDERS  = "39",
          FUNDAMENTAL_DATA  = "40",
          DELTA_NEUTRAL  = "40",
          CONTRACT_DATA_CHAIN  = "40",
          SCALE_ORDERS2  = "40",
          ALGO_ORDERS  = "41",
          EXECUTION_DATA_CHAIN  = "42",
          NOT_HELD  = "44",
          SEC_ID_TYPE  = "45",
          PLACE_ORDER_CONID  = "46",
          REQ_MKT_DATA_CONID  = "47",
          REQ_CALC_IMPLIED_VOLAT  = "49",
          REQ_CALC_OPTION_PRICE  = "50",
          CANCEL_CALC_IMPLIED_VOLAT  = "50",
          CANCEL_CALC_OPTION_PRICE  = "50",
          SSHORTX_OLD  = "51",
          SSHORTX  = "52",
          REQ_GLOBAL_CANCEL  = "53",
          HEDGE_ORDERS  = "54",
          REQ_MARKET_DATA_TYPE  = "55",
          OPT_OUT_SMART_ROUTING  = "56",
          SMART_COMBO_ROUTING_PARAMS  = "57",
          DELTA_NEUTRAL_CONID  = "58",
          SCALE_ORDERS3  = "60",
          ORDER_COMBO_LEGS_PRICE  = "61",
          TRAILING_PERCENT  = "62",
          DELTA_NEUTRAL_OPEN_CLOSE  = "66",
          ACCT_SUMMARY  = "67",
          TRADING_CLASS  = "68",
          SCALE_TABLE  = "69",
          LINKING  = "70",
          ALGO_ID  = "71",
          OPTIONAL_CAPABILITIES  = "72",
          ORDER_SOLICITED  = "73",
          LINKING_AUTH  = "74",
          PRIMARYEXCH  = "75",
          RANDOMIZE_SIZE_AND_PRICE  = "76",
          FRACTIONAL_POSITIONS  = "101",
          PEGGED_TO_BENCHMARK  = "102",
          MODELS_SUPPORT  = "103",
          SEC_DEF_OPT_PARAMS_REQ  = "104",
          EXT_OPERATOR  = "105",
          SOFT_DOLLAR_TIER  = "106",
          REQ_FAMILY_CODES  = "107",
          REQ_MATCHING_SYMBOLS  = "108",
          PAST_LIMIT  = "109",
          MD_SIZE_MULTIPLIER  = "110",
          CASH_QTY  = "111",
          REQ_MKT_DEPTH_EXCHANGES  = "112",
          TICK_NEWS  = "113",
          SMART_COMPONENTS  = "114",
          REQ_NEWS_PROVIDERS  = "115",
          REQ_NEWS_ARTICLE  = "116",
          REQ_HISTORICAL_NEWS  = "117",
          REQ_HEAD_TIMESTAMP  = "118",
          REQ_HISTOGRAM_DATA  = "119",
          SERVICE_DATA_TYPE  = "120",
          AGG_GROUP  = "121",
          UNDERLYING_INFO  = "122",
          CANCEL_HEADTIMESTAMP  = "123",
          SYNT_REALTIME_BARS  = "124",
          CFD_REROUTE  = "125",
          MARKET_RULES  = "126",
          PNL  = "127",
          NEWS_QUERY_ORIGINS  = "128",
          UNREALIZED_PNL  = "129",
          HISTORICAL_TICKS  = "130",
          MARKET_CAP_PRICE  = "131",
          PRE_OPEN_BID_ASK  = "132",
          REAL_EXPIRATION_DATE  = "134",
          REALIZED_PNL  = "135",
          LAST_LIQUIDITY  = "136",
          TICK_BY_TICK  = "137",
          DECISION_MAKER  = "138",
          MIFID_EXECUTION  = "139",
          TICK_BY_TICK_IGNORE_SIZE  = "140",
          AUTO_PRICE_FOR_HEDGE  = "141",
          WHAT_IF_EXT_FIELDS  = "142",
          SCANNER_GENERIC_OPTS  = "143",
          API_BIND_ORDER  = "144",
          ORDER_CONTAINER  = "145",
          SMART_DEPTH  = "146",
          REMOVE_NULL_ALL_CASTING  = "147",
          D_PEG_ORDERS  = "148",
          MKT_DEPTH_PRIM_EXCHANGE  = "149",
          COMPLETED_ORDERS  = "150",
          PRICE_MGMT_ALGO  = "151")

.EClientErrors <- list(
              ALREADY_CONNECTED = list( Code = "501", Message = "Already Connected."),
              CONNECT_FAIL  = list( Code = "502", "Could not connect to TWS. Confirm that --Enable ActiveX and Socket Clients--  is enabled and connection port is the same as --Socket Port-- on the TWS --Edit->Global Configuration...->API->Settings-- menu.  Live Trading ports: TWS: 7496  IB Gateway: 4001. Simulated Trading ports for installations of version 954.1 or newer: TWS: 7497  IB Gateway: 4002"),
              UPDATE_TWS  = list( Code = "503", Message = "The TWS is out of date and must be upgraded."),
              NOT_CONNECTED  = list( Code = "504", Message = "Not connected"),
              UNKNOWN_ID  = list( Code = "505", Message = "Fatal Error: Unknown message id."),
              FAIL_SEND_REQMKT  = list( Code = "510", Message = "Request Market Data Sending Error - "),
              FAIL_SEND_CANMKT  = list( Code = "511", Message = "Cancel Market Data Sending Error - "),
              FAIL_SEND_ORDER  = list( Code = "512", Message = "Order Sending Error - "),
              FAIL_SEND_ACCT  = list( Code = "513", Message = "Account Update Request Sending Error -"),
              FAIL_SEND_EXEC  = list( Code = "514", Message = "Request For Executions Sending Error -"),
              FAIL_SEND_CORDER  = list( Code = "515", Message = "Cancel Order Sending Error -"),
              FAIL_SEND_OORDER  = list( Code = "516", Message = "Request Open Order Sending Error -"),
              UNKNOWN_CONTRACT  = list( Code = "517", Message = "Unknown contract. Verify the contract details supplied."),
              FAIL_SEND_REQCONTRACT  = list( Code = "518", Message = "Request Contract Data Sending Error - "),
              FAIL_SEND_REQMKTDEPTH  = list( Code = "519", Message = "Request Market Depth Sending Error - "),
              FAIL_SEND_CANMKTDEPTH  = list( Code = "520", Message = "Cancel Market Depth Sending Error - "),
              FAIL_SEND_SERVER_LOG_LEVEL  = list( Code = "521", Message = "Set Server Log Level Sending Error - "),
              FAIL_SEND_FA_REQUEST  = list( Code = "522", Message = "FA Information Request Sending Error - "),
              FAIL_SEND_FA_REPLACE  = list( Code = "523", Message = "FA Information Replace Sending Error - "),
              FAIL_SEND_REQSCANNER  = list( Code = "524", Message = "Request Scanner Subscription Sending Error - "),
              FAIL_SEND_CANSCANNER  = list( Code = "525", Message = "Cancel Scanner Subscription Sending Error - "),
              FAIL_SEND_REQSCANNERPARAMETERS  = list( Code = "526", Message = "Request Scanner Parameter Sending Error - "),
              FAIL_SEND_REQHISTDATA  = list( Code = "527", Message = "Request Historical Data Sending Error - "),
              FAIL_SEND_CANHISTDATA  = list( Code = "528", Message = "Request Historical Data Sending Error - "),
              FAIL_SEND_REQRTBARS  = list( Code = "529", Message = "Request Real-time Bar Data Sending Error - "),
              FAIL_SEND_CANRTBARS  = list( Code = "530", Message = "Cancel Real-time Bar Data Sending Error - "),
              FAIL_SEND_REQCURRTIME  = list( Code = "531", Message = "Request Current Time Sending Error - "),
              FAIL_SEND_REQFUNDDATA  = list( Code = "532", Message = "Request Fundamental Data Sending Error - "),
              FAIL_SEND_CANFUNDDATA  = list( Code = "533", Message = "Cancel Fundamental Data Sending Error - "),
              FAIL_SEND_REQCALCIMPLIEDVOLAT  = list( Code = "534", Message = "Request Calculate Implied Volatility Sending Error - "),
              FAIL_SEND_REQCALCOPTIONPRICE  = list( Code = "535", Message = "Request Calculate Option Price Sending Error - "),
              FAIL_SEND_CANCALCIMPLIEDVOLAT  = list( Code = "536", Message = "Cancel Calculate Implied Volatility Sending Error - "),
              FAIL_SEND_CANCALCOPTIONPRICE  = list( Code = "537", Message = "Cancel Calculate Option Price Sending Error - "),
              FAIL_SEND_REQGLOBALCANCEL  = list( Code = "538", Message = "Request Global Cancel Sending Error - "),
              FAIL_SEND_REQMARKETDATATYPE  = list( Code = "539", Message = "Request Market Data Type Sending Error - "),
              FAIL_SEND_REQPOSITIONS  = list( Code = "540", Message = "Request Positions Sending Error - "),
              FAIL_SEND_CANPOSITIONS  = list( Code = "541", Message = "Cancel Positions Sending Error - "),
              FAIL_SEND_REQACCOUNTDATA  = list( Code = "542", Message = "Request Account Data Sending Error - "),
              FAIL_SEND_CANACCOUNTDATA  = list( Code = "543", Message = "Cancel Account Data Sending Error - "),
              FAIL_SEND_VERIFYREQUEST  = list( Code = "544", Message = "Verify Request Sending Error - "),
              FAIL_SEND_VERIFYMESSAGE  = list( Code = "545", Message = "Verify Message Sending Error - "),
              FAIL_SEND_QUERYDISPLAYGROUPS  = list( Code = "546", Message = "Query Display Groups Sending Error - "),
              FAIL_SEND_SUBSCRIBETOGROUPEVENTS  = list( Code = "547", Message = "Subscribe To Group Events Sending Error - "),
              FAIL_SEND_UPDATEDISPLAYGROUP  = list( Code = "548", Message = "Update Display Group Sending Error - "),
              FAIL_SEND_UNSUBSCRIBEFROMGROUPEVENTS  = list( Code = "549", Message = "Unsubscribe From Group Events Sending Error - "),
              BAD_LENGTH  = list( Code = "507", Message = "Bad message length"),
              BAD_MESSAGE  = list( Code = "508", Message = "Bad message"),
              UNSUPPORTED_VERSION  = list( Code = "506", Message = "Unsupported version"),
              FAIL_SEND_VERIFYANDAUTHREQUEST  = list( Code = "551", Message = "Verify And Auth Request Sending Error - "),
              FAIL_SEND_VERIFYANDAUTHMESSAGE  = list( Code = "552", Message = "Verify And Auth Message Sending Error - "),
              FAIL_SEND_REQPOSITIONSMULTI  = list( Code = "553", Message = "Request Positions Multi Sending Error - "),
              FAIL_SEND_CANPOSITIONSMULTI  = list( Code = "554", Message = "Cancel Positions Multi Sending Error - "),
              FAIL_SEND_REQACCOUNTUPDATESMULTI  = list( Code = "555", Message = "Request Account Updates Multi Sending Error - "),
              FAIL_SEND_CANACCOUNTUPDATESMULTI  = list( Code = "556", Message = "Cancel Account Updates Multi Sending Error - "),
              FAIL_SEND_REQSECDEFOPTPARAMS  = list( Code = "557", Message = "Request Security Definition Option Parameters Sending Error - "),
              FAIL_SEND_REQSOFTDOLLARTIERS  = list( Code = "558", Message = "Request Soft Dollar Tiers Sending Error - "),
              FAIL_SEND_REQFAMILYCODES  = list( Code = "559", Message = "Request Family Codes Sending Error - "),
              FAIL_SEND_REQMATCHINGSYMBOLS  = list( Code = "560", Message = "Request Matching Symbols Sending Error - "),
              FAIL_SEND_REQMKTDEPTHEXCHANGES  = list( Code = "561", Message = "Request Market Depth Exchanges Sending Error - "),
              FAIL_SEND_REQSMARTCOMPONENTS  = list( Code = "562", Message = "Request Smart Components Sending Error - "),
              FAIL_SEND_REQNEWSPROVIDERS  = list( Code = "563", Message = "Request News Providers Sending Error - "),
              FAIL_SEND_REQNEWSARTICLE  = list( Code = "564", Message = "Request News Article Sending Error - "),
              FAIL_SEND_REQHISTORICALNEWS  = list( Code = "565", Message = "Request Historical News Sending Error - "),
              FAIL_SEND_REQHEADTIMESTAMP  = list( Code = "566", Message = "Request Head Time Stamp Sending Error - "),
              FAIL_SEND_REQHISTOGRAMDATA  = list( Code = "567", Message = "Request Histogram Data Sending Error - "),
              FAIL_SEND_CANCELHISTOGRAMDATA  = list( Code = "568", Message = "Cancel Request Histogram Data Sending Error - "),
              FAIL_SEND_CANCELHEADTIMESTAMP  = list( Code = "569", Message = "Cancel Head Time Stamp Sending Error - "),
              FAIL_SEND_REQMARKETRULE  = list( Code = "570", Message = "Request Market Rule Sending Error - "),
              FAIL_SEND_REQPNL  = list( Code = "571", Message = "Request PnL Sending Error - "),
              FAIL_SEND_CANCELPNL  = list( Code = "572", Message = "Cancel PnL Sending Error - "),
              FAIL_SEND_REQPNLSINGLE  = list( Code = "573", Message = "Request PnL Single Error - "),
              FAIL_SEND_CANCELPNLSINGLE  = list( Code = "574", Message = "Cancel PnL Single Sending Error - "),
              FAIL_SEND_REQHISTORICALTICKS  = list( Code = "575", Message = "Request Historical Ticks Error - "),
              FAIL_SEND_REQTICKBYTICKDATA  = list( Code = "576", Message = "Request Tick-By-Tick Data Sending Error - "),
              FAIL_SEND_CANCELTICKBYTICKDATA  = list( Code = "577", Message = "Cancel Tick-By-Tick Data Sending Error - "),
              FAIL_SEND_REQCOMPLETEDORDERS  = list( Code = "578", Message = "Request Completed Orders Sending Error - "),
              FAIL_GENERIC  = list( Code = "-1", Message = "Specific error message needs to be given for these requests! ")
)



CodeMsgPair <- function(Eclient){
  print(Eclient$Message)
  return(Eclient$Code)
}



































`.twsERR` <-
structure(c("Max rate of messages per second has been exceeded.", 
"Max number of tickers has been reached.", "Duplicate ticker ID.", 
"Duplicate order ID.", "Can't modify a filled order.", "Order being modified does not match original order.", 
"Can't transmit order ID.", "Cannot transmit incomplete order.", 
"Price is out of the range defined by the Percent Setting at order defaults frame. The order will not be transmitted.", 
"The price does not conform to the minimum price variation for this contract.", 
"The Time in force (tif type) and the order type are incompatible.", 
"The Tif option should be set to DAY for MOC and LOC orders.", 
"Relative orders are valid for stocks only.", "Relative orders for US stocks can only be submitted to SMART, SMART_ECN, INSTINET, or PRIMEX.", 
"The order cannot be transmitted to a dead exchange.", "The block order size must be at least 50.", 
"VWAP orders must be routed through the VWAP exchange.", "Only VWAP orders may be placed on the VWAP exchange.", 
"It is too late to place a VWAP order for today.", "Invalid BD flag for the order. Check \"Destination\" and \"BD\" flag.", 
"No request tag has been found for order:", "No record is available for conid:", 
"No market rule is available for conid:", "Buy price must be the same as the best asking price.", 
"Sell price must be the same as the best bidding price.", "Linkage orders are not supported on this exchange.", 
"Linkage customers cannot submit non-linkage orders for options.", 
"VWAP orders must be submitted at least three minutes before the start time.", 
"The sweep-to-fill flag and display size are only valid for US stocks routed through SMART, and will be ignored.", 
"This order cannot be transmitted without a clearing account.", 
"Submit new order failed.", "Modify order failed.", "Can't find order with ID =", 
"This order cannot be cancelled.", "VWAP orders can only be cancelled up to three minutes before the start time.", 
"Could not parse ticker request.", "Parsing error:", "The size value should be an integer:", 
"The price value should be a double:", "Institutional customer account does not have account info", 
"Requested ID is not an integer number.", "Order size does not match total share allocation.", 
"Error in validating entry fields.", "Invalid trigger method.", 
"The conditional contract info is incomplete.", "A conditional order can only be submitted when the order type is set to limit or market.", 
"This order cannot be transmitted without a user name.", "The \"hidden\" order attribute may not be specified for this order.", 
"EFPs can only be limit orders.", "Orders cannot be transmitted for a halted security.", 
"A sizeOp order must have a username and account.", "A SizeOp order must go to IBSX", 
"An order can be EITHER Iceberg or Discretionary. Please remove either the Discretionary amount or the Display size.", 
"You must specify an offset amount or a percent offset value.", 
"The percent offset value must be between 0% and 100%.", "The size value cannot be zero.", 
"Cancel attempted when order is not in a cancellable state. Order permId =", 
"Historical market data Service error message.", "Historical market Data Service query message.", 
"HMDS Expired Contract Violation.", "VWAP order time must be in the future.", 
"Discretionary amount does not conform to the minimum price variation for this contract.", 
"No security definition has been found for the request.", "Order rejected - Reason:", 
"Order cancelled - Reason:", "The security (   ) is not available or allowed for this account.", 
"Can't find EId with ticker Id:", "Invalid ticker action:", "Error parsing stop ticker string", 
"Invalid action:", "Invalid acct. value action:", "Request parsing error, the request has been ignored.", 
"Error processing DDE request.", "Invalid request topic.", "Unable to create the 'API' page in TWS as the maximum number of pages already exists.", 
"Max number (3) of market depth requests has been reached.", 
"Can't find the subscribed market depth with tickerId:", "The origin is invalid.", 
"The combo details are invalid.", "The combo details for leg '<leg number>' are invalid.", 
"Security type 'BAG' requires combo leg details.", "Stock combo legs are restricted to SMART order routing.", 
"Market depth data has been HALTED. Please re-subscribe.", "Market depth data has been RESET. Please empty deep book contents before applying any new entries.", 
"Advisors cannot modify partially filled orders.", "Attempt to set the server log level failed as the log level was invalid.", 
"Server error when reading an API client request.", "Server error when validating an API client request.", 
"Server error when processing an API client request.", "Server error: cause - %s", 
"Server error when reading a DDE client request - missing data.", 
"Discretionary orders are not supported for this combination of exchange and order type.", 
"Unable connect as the client id is already in use. Retry with a unique client id.", 
"Only API connections with clientId set to 0 can set the auto bind TWS orders property.", 
"Trailing stop orders can be attached to limit or stop-limit orders only.", 
"Order modify failed. Cannot change to the new order type.", 
"Only FA or STL customers can request managed accounts list.", 
"Internal error. FA or STL does not have any managed accounts.", 
"The account codes for the order profile are invalid.", "Invalid share allocation syntax.", 
"Invalid Good Till Date order", "Invalid delta: The delta must be between 0 and 100.", 
"Invalid Expiration Time.", "Invalid Good After Time.", "Good After Time Disabled.", 
"Futures spread no longer supported.", "Invalid improvement amount.", 
"Invalid delta.", "Invalid Peg.", "Invalid Good Till Date.", 
"The account is not a financial advisor account", "Invalid FA inter-market combo order.", 
"Not an institutional account.", "Invalid short slot value.", 
"Not a short sale.", "Invalid GAT inter-market combo.", "Invalid minimum quantity for inter-market combo.", 
"Invalid RTH only designation.", "Bad short slot location.", 
"Short slot location specified.", "Not subscribed to market data.", 
"Order size incorrect.", "Smart-combo OCA not supported.", "Your client version is out of date.", 
"Smart combo child not supported.", "Native combo OCA is incompatible.", 
"What- if check not supported for this Smart inter-market combo.", 
"Invalid trigger price.", "Invalid adjusted stop price.", "Invalid adjusted stop limit price.", 
"Invalid adjusted trailing amount.", "No scanner subscription found for ticker id:", 
"No historical data query found for ticker id:", "Volatility type if set must be 1 or 2 for VOL orders.", 
"Reference Price Type must be 1 or 2 for dynamic volatility management.", 
"Volatility orders are only valid for US options.", "Dynamic Volatility orders must be SMART routed, or trade on a Price Improvement Exchange.", 
"VOL order requires positive floating point value for volatility.", 
"Cannot set dynamic VOL attribute on non-VOL order.", "Can only set stock range attribute on VOL or PEGGED TO STOCK order.", 
"If both are set, the lower stock range attribute must be less than the upper stock range attribute.", 
"Stock range attributes cannot be negative.", "The order is not eligible for continuous update. The option must trade on a cheap-to-reroute exchange.", 
"Must specify valid delta hedge order aux. price.", "Delta hedge order type requires delta hedge aux. price to be specified.", 
"Delta hedge order type requires that no delta hedge aux. price be specified.", 
"This order type is not allowed for delta hedge orders.", "Your DDE.dll needs to be upgraded.", 
"The price specified violates the number of ticks constraint specified in the default order settings.", 
"The size specified violates the size constraint specified in the default order settings.", 
"Invalid DDE array request.", "Duplicate ticker ID for API scanner subscription.", 
"Duplicate ticker ID for API historical data query.", "Unsupported order type for this exchange and security type.", 
"Order size is smaller than the minimum requirement.", "Supplied routed order ID is not unique.", 
"Supplied routed order ID is invalid.", "Invalid date for GTD.", 
"This order is invalid since is uses an expired contract.", "The short slot order has not delta hedge order type.", 
"Invalid process time.", "Direct routed OCA error.", "Direct routed order type error.", 
"Region order type error.", "Direct routed condition error placeholder.", 
"Order message error", "Algo order error.", "Length restriction.", 
"Conditions are not allowed for this contract.", "Invalid stop price.", 
"Allowed quantity message.", "The child order quantity should be equivalent to the parent order size.", 
"The currency (  ) is not allowed.", "The symbol should contain valid non-unicode characters only.", 
"Invalid scale order increment.", "Invalid scale order. You must specify order component size.", 
"Invalid subsequent component size for scale order.", "Invalid outside RTH.", 
"The contract is not available for trading.", "What-if order should have the transmit flag set to true.", 
"Do not use generic ticks for snapshot market data.", "RFQ already sent for the conid.", 
"RFQ not applicable for the contract. Order ID:", "Invalid initial component size for scale order.", 
"Invalid scale order profit offset.", "Missing initial component size for scale order.", 
"Invalid real-time query.", "Invalid route.", "Invalid OMS component attributes.", 
"Already connected.", "Couldn't connect to TWS. Confirm that API is enabled in TWS via the Configure>API menu command.", 
"Your version of TWS is out of date and must be upgraded.", "Not connected.", 
"Fatal error: Unknown message id.", "Request market data - sending error:", 
"Cancel market data - sending error:", "Order - sending error:", 
"Account update request - sending error:", "Request for executions  - sending error:", 
"Cancel order - sending error:", "Request open order - sending error:", 
"Unknown contract. Verify the contract details supplied.", "Request contract data - sending error:", 
"Request market depth - sending error:", "Cancel market depth - sending error:", 
"Set server log level - sending error:", "FA Information Request - sending error:", 
"FA Information Replace - sending error:", "Request Scanner subscription - sending error:", 
"Cancel Scanner subscription - sending error:", "Request Scanner parameter - sending error:", 
"Request Historical data - sending error:", "Cancel Historical data - sending error:", 
"Request real-time bar data - sending error:", "Cancel real-time bar data - sending error:", 
"Connectivity between IB and TWS has been lost.", "Connectivity between IB and TWS has been restored- data lost.", 
"Connectivity between IB and TWS has been restored- data maintained.", 
"TWS socket port has been reset and this connection is being dropped.", 
"New account data requested from TWS.  API client has been unsubscribed from account data.", 
"Unable to subscribe to account as the following clients are subscribed to a different account.", 
"Unable to modify this order as it is still being processed.", 
"A market data farm is disconnected.", "A market data farm is connected.", 
"A historical data farm is disconnected.", "A historical data farm is connected.", 
"A historical data farm connection has become inactive but should be available upon demand.", 
"A market data farm connection has become inactive but should be available upon demand.", 
"Order Event Warning: Attribute 'Outside Regular Trading Hours' is ignored based on the order type and destination. PlaceOrder is now processed."
), .Dim = c(229L, 1L), .Dimnames = list(c("100", "101", "102", 
"103", "104", "105", "106", "107", "109", "110", "111", "113", 
"114", "115", "116", "117", "118", "119", "120", "121", "122", 
"123", "124", "125", "126", "127", "128", "129", "131", "132", 
"133", "134", "135", "136", "137", "138", "139", "140", "141", 
"142", "143", "144", "145", "146", "147", "148", "151", "152", 
"153", "154", "155", "156", "157", "158", "159", "160", "161", 
"162", "165", "166", "167", "168", "200", "201", "202", "203", 
"300", "301", "302", "303", "304", "305", "306", "307", "308", 
"309", "310", "311", "312", "313", "314", "315", "316", "317", 
"318", "319", "320", "321", "322", "323", "324", "325", "326", 
"327", "328", "329", "330", "331", "332", "333", "334", "335", 
"336", "337", "338", "339", "340", "341", "342", "343", "344", 
"345", "346", "347", "348", "349", "350", "351", "352", "353", 
"354", "355", "356", "357", "358", "359", "360", "361", "362", 
"363", "364", "365", "366", "367", "368", "369", "370", "371", 
"372", "373", "374", "375", "376", "377", "378", "379", "380", 
"381", "382", "383", "384", "385", "386", "387", "388", "389", 
"390", "391", "392", "393", "394", "395", "396", "397", "398", 
"399", "400", "401", "402", "403", "404", "405", "406", "407", 
"408", "409", "410", "411", "412", "413", "414", "415", "416", 
"417", "418", "419", "420", "421", "422", "501", "502", "503", 
"504", "505", "510", "511", "512", "513", "514", "515", "516", 
"517", "518", "519", "520", "521", "522", "523", "524", "525", 
"526", "527", "528", "529", "530", "531", "1101", "1102", "1300", 
"2100", "2101", "2102", "2103", "2104", "2105", "2106", "2107", 
"2108", "2109"), NULL))
